name: savoirguineeweb
description: Savoir Guinea website

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
   
  get_it:
  queue: ^3.1.0

  provider: 
  http: 0.12.0+4
  #url_launcher: 5.2.7
  community_material_icon:
  dio: ^3.0.10 
  dio_http_cache: 0.2.5
  pretty_dio_logger: 1.1.0
  toggle_bar: 1.0.0
  animated_text_kit: 2.0.0
  #firebase_messaging: 6.0.3
  #shared_preferences: 0.4.0
  #oauth2_custom_uri_scheme: 0.3.6
  animator: 1.0.0+3
  animated_card: 1.0.0+8
  gradient_text: 1.0.2
  carousel_slider: 1.4.1
  video_player: 0.10.4+1
  chewie_audio: 1.0.0+1
  flutter_brand_icons: 1.1.0
  flutter_screenutil: 1.0.2
  flutter_signin_button: ^1.0.0
  timeline_tile: ^1.0.0
  google_fonts: ^1.1.0
  flutter_highlight: ^0.6.0
  timeline_list: ^0.0.3
  solid_bottom_sheet: 0.1.9
  image_picker: ^0.6.5+3
  awesome_dialog: 
  get:
  avatar_letter: ^1.0.1
  dart_amqp:
  hive: ^1.4.4+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.3.0
  # shared_preferences: ^0.5.9
  uuid: 2.2.2
  socket_io:
  # socket_io_client: ^0.9.11
  # flutter_socket_io: ^0.6.0
  # web_socket_channel: ^1.1.0
  socket_io_client: ^0.9.4
  # flutter_simple_dependency_injection: ^1.0.1
  # flutter_socket_io: ^0.6.0
  # adhara_socket_io: ^0.4.2+1
  # websok: ^2.1.2
  #hexcolor: ^1.0.4
  cached_network_image: ^2.3.2+1
  # floating_bottom_navigation_bar: ^1.4.1
  # animated_bottom_navigation_bar: ^0.1.2+2
  # motion_tab_bar: ^0.1.5
  # circular_bottom_navigation: ^1.0.1
  # # like_button: ^1.0.3
  # getsocket: ^1.0.0
  # socket_io_client: ^0.9.11
  # adhara_socket_io: ^0.4.2+1
  # universal_mqtt_client: ^0.1.1
  # web_socket_channel:
  # retry: ^3.0.1
  ez_mqtt_client:
  supercharged: ^1.11.0
  flutter_screen_scaler: ^2.0.0
  font_awesome_flutter:
  featurehub_sse_client:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
